## Unified exception handling

### Backend exception handling

In the development process, it is inevitable to handle various exceptions, and exception handling methods can be seen everywhere, so there will be a lot of `try {...} catch {...} finally {...}` codes in the code Blocks will not only cause a lot of redundant code, but also affect the readability of the code, so it is necessary to uniformly handle exceptions. To this end, we define a unified exception class `mall4cloudException` and exception management class `DefaultExceptionHandlerConfig`.

Let's first look at the code of `mall4cloudException`

```java
public class mall4cloudException extends RuntimeException {

	private static final long serialVersionUID = 1L;

	private Object object;
    
	/**
	 * 响应状态码枚举
	 */
	private ResponseEnum responseEnum;

	public mall4cloudException(String msg) {
		super(msg);
	}

	public mall4cloudException(String msg, Object object) {
		super(msg);
		this.object = object;
	}

	public mall4cloudException(String msg, Throwable cause) {
		super(msg, cause);
	}


	public mall4cloudException(ResponseEnum responseEnum) {
		super(responseEnum.getMsg());
		this.responseEnum = responseEnum;
	}

	public mall4cloudException(ResponseEnum responseEnum,Object object) {
		super(responseEnum.getMsg());
		this.responseEnum = responseEnum;
		this.object = object;
	}


	public Object getObject() {
		return object;
	}

	public ResponseEnum getResponseEnum() {
		return responseEnum;
	}
}
```

`ResponseEnum` is our custom enumeration class that returns status codes, which is defined as an enumeration class, which handles the status code and exception content returned by exceptions more intuitively. For each additional exception condition in the future, you only need to add an enumeration instance. That is, there is no need to define an exception class for each exception.

```java
public enum ResponseEnum {

	/**
	 * ok
	 */
	OK("00000", "ok"),

	/**
	 * 用于直接显示提示用户的错误，内容由输入内容决定
	 */
	SHOW_FAIL("A00001", ""),

	/**
	 * 方法参数没有校验，内容由输入内容决定
	 */
	METHOD_ARGUMENT_NOT_VALID("A00002", ""),

	/**
	 * 无法读取获取请求参数
	 */
	HTTP_MESSAGE_NOT_READABLE("A00003", "请求参数格式有误"),

	/**
	 * 未授权
	 */
	UNAUTHORIZED("A00004", "Unauthorized"),

	/**
	 * 服务器出了点小差
	 */
	EXCEPTION("A00005", "服务器出了点小差");
    
    private final String code;

	private final String msg;

	public String value() {
		return code;
	}

	public String getMsg() {
		return msg;
	}

	ResponseEnum(String code, String msg) {
		this.code = code;
		this.msg = msg;
	}

	@Override
	public String toString() {
		return "ResponseEnum{" + "code='" + code + '\'' + ", msg='" + msg + '\'' + "} " + super.toString();
	}

}
```

Let's take a look at the `DefaultExceptionHandlerConfig` class

```java
@RestController
@RestControllerAdvice
public class DefaultExceptionHandlerConfig {

	private static final Logger logger = LoggerFactory.getLogger(DefaultExceptionHandlerConfig.class);

	@ExceptionHandler(mall4cloudException.class)
	public ResponseEntity<ServerResponseEntity<Object>> mall4cloudExceptionHandler(mall4cloudException e) {
		logger.error("mall4cloudExceptionHandler", e);

		ResponseEnum responseEnum = e.getResponseEnum();
		// 失败返回失败消息 + 状态码
		if (responseEnum != null) {
			return ResponseEntity.status(HttpStatus.OK).body(ServerResponseEntity.fail(responseEnum, e.getObject()));
		}
		// 失败返回消息 状态码固定为直接显示消息的状态码
		return ResponseEntity.status(HttpStatus.OK).body(ServerResponseEntity.showFailMsg(e.getMessage()));
	}
}
```

---

### Front-end exception handling

The front-end request and the corresponding package are encapsulated, and the content of the request response will be intercepted by the interceptor. When the background returns to the front-end with a specific status code, the front-end will display different error messages. Request-response is very common, we look at one of the code in `src\utils\request.js`

```javascript
service.interceptors.response.use(
  response => {
    const res = response.data

    if (res.code === '00000') {
      return res.data
    }

    // A00001 用于直接显示提示用户的错误，内容由输入内容决定
    // A00003 无法读取获取请求参数
    if (res.code === 'A00001' || res.code === 'A00003' || res.code === 'A00005') {
      Message({
        message: res.msg || 'Error',
        type: 'error',
        duration: 1.5 * 1000
      })
      return Promise.reject(res)
    }

    // A00002 方法参数没有校验，内容由输入内容决定
    if (res.code === 'A00002') {
      if (res.data && res.data.length) {
        res.data.forEach(errorMsg => {
          Message({
            message: errorMsg || 'Error',
            type: 'error',
            duration: 1.5 * 1000
          })
        })
      } else {
        Message({
          message: res.msg || 'Error',
          type: 'error',
          duration: 1.5 * 1000
        })
      }
      return Promise.reject()
    }

    // A00004 未授权
    if (res.code === 'A00004') {
      // to re-login
      MessageBox.confirm('您已注销，您可以取消停留在该页上，或重新登录', '确认注销', {
        confirmButtonText: '重新登陆',
        cancelButtonText: '取消',
        type: 'warning'
      }).then(() => {
        store.dispatch('user/resetToken').then(() => {
          location.reload()
        })
      })
      return Promise.reject()
    }
    return Promise.reject(res)
  },
  error => {
    console.log('err' + error) // for debug
    Message({
      message: error.message,
      type: 'error',
      duration: 1.5 * 1000
    })
    return Promise.reject(error)
  }
)
```

Here, the returned status code such as `A00001` will be uniformly intercepted, and an error message will be displayed.
